### ISSUE TITLE
Game crashes when creating a normal waypoint.

### ISSUE THREAD

**Issue by Gummar** [CCNHsK-Dev/SyPB#1]
In waypoint edit mode, creating a normal waypoint through "+use" or through "sypb waypoint menu" will make the game crash to desktop. Playing Zombie Plague with sypb_gamemode 2.

**Comment by CCNHsK-Dev** [comment]
ok, thx your report :) I would fixed this 
And then, SyPB have new edit waypoint mode, you can input sypb sgdwp on 
to edit your waypoint

**Comment by CCNHsK-Dev** [comment]
Hey, I test about add waypoint will crash to desktop. 
(Testing SyPB Build is 1.39.31275.499)

But I will not have this problem. 
Can you send the .mdmp file to me?
(OneDrive or Dropbox, Thabk you)

**Comment by Gummar** [comment]
Ok, found the problem, it is a problem related to config files, I was using old sypb config files for the newest version. I couldn't find a mdmp file anywhere, so I will leave my sypb folder here (for some reason dropbox is offline for me, so I'm posting on mega.nz):
https://mega.nz/#!jUNF1Yob!mtapt9iUdwy__7g2RW5eohl23C_j2lH9zMdT5CeGl2U
It also crashes when loading a map that doesn't have a waypoint file for it.

**Comment by CCNHsK-Dev** [comment]
oh, this is easy :)
You can use new version files (delete 'sypb' folder and install new version folder)
or 
Delete 'sypb/game_data' file and add 'sypb/logs' file

I think this would fixed your problem :+1:

**Comment by Gummar** [comment]
Well, I already fixed it by using WinMerge and merging new files with the old files' differences. Not sure if I should close the issue, as you can add some file check code to check if everything is alright.

**Comment by CCNHsK-Dev** [comment]
I will not add check code about check the folder....
Because this need use 'windows.h' or 'io.h' (have not use this now)

I think this may be waste of resources
Because the folder is base data.. (eg: waypoint folder // etc....)

**Comment by Gummar** [comment]
Ok, I had the problem again, but at least at this time I found the issue, I usually delete empty folders after installing stuff, I deleted the "sypb/logs" folder, when you create a waypoint, the game tries to write something to a file inside the "sypb/logs" folder, but because the "sypb/logs" folder didn't exist, the game would crash.
