### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by HellMan2023** [CCNHsK-Dev/SyPB#14]
@CCNHsK-Dev, Hello, I wanted to ask you when will you approximately release SyPB 1.50 bots to the public?It's just been a long time, and no news from you.

**Comment by CCNHsK-Dev** [comment]
You can get lastly build on here
https://github.com/CCNHsK-Dev/SyPB/tree/master/Project%20SyPB/Project_OutPut

this is 29/5/2023 build.
I'm busy now, I don't sure when can I come back.

But, If you find every bugs on lastly build, you can report on here, I will check it.

**Comment by HellMan2023** [comment]
Thank you. We will look forward to your return.

**Comment by HellMan2023** [comment]
@CCNHsK-Dev, By the way, it would be nice if you wrote a complete list of your bot settings with a detailed description, for example, on the main page. This is very necessary, because when you release a mini update, we simply cannot know if you added or changed any cvar. And just as you make a new setting or change the current one, you will update this list so that everyone understands. I suggest doing this until you release version 1.50.

Do you agree?
🥺

**Comment by MysticDeathProject** [comment]
no all cvars will be in sypb.cfg
