### ISSUE TITLE
Question about dependency

### ISSUE THREAD

**Issue by ijustwanttousegithub** [CCNHsK-Dev/SyPB#15]
SyPB failed to load or not detected after this commit:
"https://github.com/CCNHsK-Dev/SyPB/commit/c4fc6f4ff7d41a2292536e18195b83eb959fb4ef"

To get it working i need to download the entire visual studio with c++ package, what dependency is needed? i tried every VC Redist but failed.

**Comment by CCNHsK-Dev** [comment]
so, on the lastly build, your problem is available too? 
I will test about it on my old pc.

**Comment by ijustwanttousegithub** [comment]
> so, on the lastly build, your problem is available too? I will test about it on my old pc.

Yes. The problem start after this commit, before this commit everything works fine. The files used are on the Project_Output folder. To replicate this either use fresh installed windows 10/11 or have no visual studio installed.

**Comment by ijustwanttousegithub** [comment]
Also i think the op of issue #11 has this same problem for his friend.

**Comment by CCNHsK-Dev** [comment]
ok, I will check about this

**Comment by CCNHsK-Dev** [comment]
Fixed

**Comment by CCNHsK-Dev** [comment]
This is my VS setting problem. 
I fixed it today, pls try it.
