### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by HellMan2023** [CCNHsK-Dev/SyPB#8]
@CCNHsK-Dev,
Hello, my friend. Could you update the configs of your bots and upload them as an archive? Thanks.

**Comment by CCNHsK-Dev** [comment]
I will post the full file on 1.50 aliveable, you can download the 1.49 full version on the blog, and get the dev build dll file on GitHub.

**Comment by HellMan2023** [comment]
> Я опубликую полный файл на 1.50 liveable, вы можете скачать полную версию 1.49 в блоге и получить dll-файл dev build на GitHub.

I just already downloaded the whole package and the latest updates of the .dll files from here, but I noticed that not all cvars were written in the .cfg file, and therefore I had to write them myself. And in the config with the bot settings, nothing is signed, and therefore it is not clear which setting is responsible for what.
That's why I decided to ask you about this.

**Comment by HellMan2023** [comment]
> I will post the full file on 1.50 aliveable, you can download the 1.49 full version on the blog, and get the dev build dll file on GitHub.

I just already downloaded the whole package and the latest updates of the .dll files from here, but I noticed that not all cvars were written in the .cfg file, and therefore I had to write them myself. And in the config with the bot settings, nothing is signed, and therefore it is not clear which setting is responsible for what.
That's why I decided to ask you about this.

**Comment by CCNHsK-Dev** [comment]
on lastly build CVAR:
sypb_debuggoal // Test cvar, set the bot goal waypoint id
sypb_followuser // Max follow bot (to radio > follow me)
sypb_knifemode // Knife Mode
sypb_spraypaints // Bot use specifies
sypb_restrictweapons // restrict weapons
sypb_chat // Bot Chat function
sypb_radio // Bot use radio
sypb_forceteam // force team
sypb_quota // Bot quota (eg, 19 = 19 sypb)
sypb_auto_players // bot&player quota (eg, 20, has 2 human player, will add 18 sypb / has 10 human players, add 10 sypb)
sypb_quota_save // Save the bot quota to sypb.cfg
sypb_difficulty // sypb difficulty
sypb_tagbots // ping is "bot"
sypb_nametag // Name Tag [SyPB]
sypb_join_after_player // sypb join after player
sypb_debug // Debug Mode
sypb_password // for ser
sypb_password_key // for ser
sypb_download_waypoint // Download waypoint file on Github function
sypb_language // language
sypb_version // SyPB Version
sypb_lockzbot // Try to lock Zbot
sypb_gamemod // Game Mode, 0 = base, 1 = dm, 2 = zp, 3 = no team, 4 = zh
sypb_ignore_enemies // sypb miss all enemy
sypb_stopbots // step the bot
sypb_zmdelay_time // zm only, set the round start delay time (zp4.3/5.0 auto set)
sypb_showwp // show the waypoint point
sypb_dangerfactor // for sypb waypoint
sypb_apitestmsg // for SyPB AMXX API testing
sypb_welcomemsg // server on sypb msg

**Comment by HellMan2023** [comment]
@CCNHsK-Dev,
Fine. What about **general.cfg**? Can you explain how to set up this config, please?

And by the way, have you seen the ZMT-BOTS release video? What was demonstrated in this video is simply incredible, but it's a pity that they were not made for the standard Zombie Plague mod + they are paid. I hope that the intelligence of your bots will be just as good.

**Comment by CCNHsK-Dev** [comment]
About general.cfg, you don't need change it, this is base mode bot buy weapon data and about bot attack delay data.

About ZMT-BOTS, I find this, 
https://zmt-bots.blogspot.com/
On the blog, ZMT-BOTS base on SyPB, but this is not free & don't open source.

Also, I think you can try about it, 
https://github.com/EfeDursun125/CS-EBOT @EfeDursun125
This is new bot for zombie mode. and the bot keep fast update.
I need working, so SyPB update will slow :(

**Comment by HellMan2023** [comment]
@CCNHsK-Dev,

> About general.cfg, you don't need change it, this is base mode bot buy weapon data and about bot attack delay data.

OK, thank you.


> About ZMT-BOTS, I find this,
> https://zmt-bots.blogspot.com/
> On the blog, ZMT-BOTS base on SyPB, but this is not free & don't open source.

Yes, this is the same post. There is a video that shows them in action, and the intelligence of these bots is amazing. It is a pity that there is no free analogue yet with a lot of waypoints and a minimum number of bugs     ( T_T)


> Also, I think you can try about it,
> https://github.com/EfeDursun125/CS-EBOT @EfeDursun125
> This is new bot for zombie mode. and the bot keep fast update.
> I need working, so SyPB update will slow :(

It would be worth a try, but these bots are quite "raw", that is, at the beginning of their development and therefore they will certainly have many bugs and flaws, and I will install them on the server. Well, their waypoint database is also not impressive.
