### ISSUE TITLE
[REQUEST] Bring back the bots ability to use grenades

### ISSUE THREAD

**Issue by ijustwanttousegithub** [CCNHsK-Dev/SyPB#9]
It would be cool to see the SyPB bots do this like the E-Bot do

**Comment by CCNHsK-Dev** [comment]
I remove use grenades because on the different game mode, grenades has different function.
If I have time, I maybe will add the grenades function on base mode, zombie mode I don't sure about it.

**Comment by CCNHsK-Dev** [comment]
Close: Not Reply
